# Generated by Django 4.0.1 on 2022-01-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('session_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('host_client_id', models.UUIDField(editable=False)),
                ('guest_client_id', models.UUIDField(editable=False)),
                ('game_state', models.JSONField()),
            ],
        ),
    ]
