# Generated by Django 4.0.1 on 2022-01-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameserver', '0002_websocketmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(editable=False)),
                ('client_id', models.UUIDField(editable=False)),
                ('timestamp', models.IntegerField(editable=False)),
                ('serialized_save', models.TextField(editable=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='gamesave',
            constraint=models.UniqueConstraint(fields=('session_id', 'client_id'), name='UQ_GAMESAVE_SESSION_ID_CLIENT_ID'),
        ),
    ]
