# Generated by Django 4.0.1 on 2022-01-16 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameserver', '0003_gamesave_gamesave_uq_gamesave_session_id_client_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameSession',
        ),
    ]
